### ISSUE TITLE
libdc1394 error: Failed to initialize libdc1394

### ISSUE THREAD

**Issue by naokiiiii** [team4gentleman/chainerapp#5]
「dlbin/dl_1_init.sh」 内の「compute_mean.py」部分で以下のエラーが発生している。
個別手動で実行する分にはエラーは発生しない。docker imageをクリーンビルドしてみたが、状況変わらず。

---

NG ->
root:/opt/t4j/chainerapp# ./dlbin/dl_1_init.sh 
~
[START] compute_mean
1Traceback (most recent call last):
  File "./compute_mean.py", line 25, in <module>
    sum_image += image
ValueError: operands could not be broadcast together with shapes (3,225,225) (3,259,194) (3,225,225) 
[START] crop
libdc1394 error: Failed to initialize libdc1394
~

OK ->
root:/opt/t4j/chainerapp#  python ./python/compute_mean.py -o /var/opt/t4j/chainer-data/mean.npy /var/opt/t4j/chainer-data/train.txt
20

**Comment by takao-s** [comment]
シェルとコマンド直接だと、numpy.asarrayの返す配列の内容が異なっていることが直接の原因
引き続き調査します

**Comment by naokiiiii** [comment]
そういうことでしたか。対応有難うございました。
